const ZH: Record<string, string> = {
  'algeria': '阿尔及利亚',
  'argentina': '阿根廷',
  'australia': '澳大利亚',
  'austria': '奥地利',
  'belgium': '比利时',
  'bosnia and herzegovina': '波黑',
  'brazil': '巴西',
  'canada': '加拿大',
  'cape verde': '佛得角',
  'colombia': '哥伦比亚',
  'croatia': '克罗地亚',
  'curacao': '库拉索',
  'curaçao': '库拉索',
  'czechia': '捷克',
  'denmark': '丹麦',
  'dr congo': '刚果(金)',
  'ecuador': '厄瓜多尔',
  'egypt': '埃及',
  'england': '英格兰',
  'france': '法国',
  'germany': '德国',
  'ghana': '加纳',
  'haiti': '海地',
  'iran': '伊朗',
  'iraq': '伊拉克',
  'ivory coast': '科特迪瓦',
  'jamaica': '牙买加',
  'japan': '日本',
  'jordan': '约旦',
  'mexico': '墨西哥',
  'morocco': '摩洛哥',
  'netherlands': '荷兰',
  'new zealand': '新西兰',
  'norway': '挪威',
  'panama': '巴拿马',
  'paraguay': '巴拉圭',
  'portugal': '葡萄牙',
  'qatar': '卡塔尔',
  'saudi arabia': '沙特阿拉伯',
  'scotland': '苏格兰',
  'senegal': '塞内加尔',
  'slovakia': '斯洛伐克',
  'south africa': '南非',
  'south korea': '韩国',
  'spain': '西班牙',
  'sweden': '瑞典',
  'switzerland': '瑞士',
  'tunisia': '突尼斯',
  'türkiye': '土耳其',
  'turkey': '土耳其',
  'ukraine': '乌克兰',
  'uruguay': '乌拉圭',
  'usa': '美国',
  'uzbekistan': '乌兹别克斯坦',
  'wales': '威尔士',
};

export function teamZhName(name: string): string {
  if (!name) return name;
  return ZH[name.toLowerCase().trim()] ?? name;
}
